### ISSUE TITLE
Sample test cases for .java file?

### ISSUE THREAD

**Issue by shiraji** [a11n/lint-junit-rule#15]
Could you give me a sample test case for .java file?

``` java
@RunWith(JUnit4.class)
public class LintTestCase extends TestCase {

    @Rule
    public Lint lint = new Lint(new PermissionDispatcherDetector(), PermissionDispatcherDetector.ISSUE);

    @Test
    public void testFoo() throws Exception {
        List<Warning> lintResult = lint.files("MainActivity.java");
        assertThat(lintResult).hasWarnings(1).in("MainActivity.java");
    }
}
```

This code does not work since it claims there is no `MainActivity.java`, so changed it to

``` diff
@RunWith(JUnit4.class)
public class LintTestCase extends TestCase {

    @Rule
    public Lint lint = new Lint(new PermissionDispatcherDetector(), PermissionDispatcherDetector.ISSUE);

    @Test
    public void testFoo() throws Exception {
-        List<Warning> lintResult = lint.files("MainActivity.java");
+        List<Warning> lintResult = lint.files("MainActivity.class");
        assertThat(lintResult).hasWarnings(1).in("MainActivity.java");
    }
}
```

And now it run the test case. However, I want to test the lint for `MainActivity.java` not `MainActivity.class` because .java file contains annotations with `@Retention(RetentionPolicy.SOURCE)` which is deleted in .class in compile time.

Thanks in advance.

**Comment by a11n** [comment]
Hi and thanks for bringing this up.

I just tested it with the sample and there were no complaints finding a Java file.

Could you please post the exact stack trace?
Where have you placed the file?

**Comment by shiraji** [comment]
You can check source code https://github.com/shiraji/PermissionsDispatcher/tree/lint-test-sample/lint

## File Structure

``` shell
PermissionsDispatcher/lint/src/test
└── java
    ├── android
    │   ├── Manifest.java // mock class
    │   ├── app
    │   │   └── Activity.java // mock class
    │   └── support
    │       └── v4
    │           └── app
    │               └── ActivityCompat.java // mock class
    ├── permissions
    │   └── dispatcher
    │       └── PermissionUtils.java // mock class
    └── unittests
        ├── LintTestCase.java
        └── MainActivity.java
```

``` java
@RunWith(JUnit4.class)
public class LintTestCase extends TestCase {

    @Rule
    public Lint lint = new Lint(new PermissionDispatcherDetector(), PermissionDispatcherDetector.ISSUE);

    @Test
    public void testFoo() throws Exception {
        List<Warning> lintResult = lint.files("unittests/MainActivity.java");
        assertThat(lintResult).hasWarnings(1).in("MainActivity.java");
    }
}
```

``` java
@RuntimePermissions
public class MainActivity extends Activity {
    @NeedsPermission(Manifest.permission.CAMERA) // this annotation is gone at compile time.
    void showCamera() {
    }

    void foo() {
        showCamera();
    }
}

```

## Stack Trace

```
junit.framework.AssertionFailedError: unittests/MainActivity.java does not exist
    at com.android.testutils.SdkTestCase.getTestfile(SdkTestCase.java:464)
    at com.android.tools.lint.checks.infrastructure.LintDetectorTest.lintFiles(LintDetectorTest.java:148)
    at com.ad.android.tools.lint.LintDetectorTestWrapper.analyze(LintDetectorTestWrapper.java:32)
    at com.ad.android.tools.lint.Lint.files(Lint.java:89)
    at unittests.LintTestCase.testFoo(LintTestCase.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.ad.android.tools.lint.Lint$LintStatement.evaluate(Lint.java:108)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by a11n** [comment]
Ok, your problem is that your test resource has to be within the **test resource folder**.

When you move `java/unittests/MainActivity.java` to `resources/src/unittests/MainActivity.java` and update your test code accordingly (`lint.files("src/unittests/MainActivity.java");`) then your file will be found.

However, your test will still fail, since no warning was raised but at least 1 is expected. I'm not so deep into your code to check whether something is wrong with your `Detector` or with the Lint analysis itself.

Because sometimes, if something is configured wrong, Lint will just ignore the resources. I discovered similar issues when I wanted to test an XmlScanner but the resource was not in a "res" folder or something (that's why I moved it to "src/").

I hope this helps you further.

**Comment by shiraji** [comment]
Still get this error...

```
junit.framework.AssertionFailedError: src/unittests/MainActivity.java does not exist
    at com.android.testutils.SdkTestCase.getTestfile(SdkTestCase.java:464)
    at com.android.tools.lint.checks.infrastructure.LintDetectorTest.lintFiles(LintDetectorTest.java:148)
    at com.ad.android.tools.lint.LintDetectorTestWrapper.analyze(LintDetectorTestWrapper.java:32)
    at com.ad.android.tools.lint.Lint.files(Lint.java:89)
    at unittests.LintTestCase.testFoo(LintTestCase.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.ad.android.tools.lint.Lint$LintStatement.evaluate(Lint.java:108)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

https://github.com/shiraji/PermissionsDispatcher/tree/lint-test-sample

**Comment by a11n** [comment]
Are you running the test from within your IDE?

I just checked out your code and ran the tests with `./gradlew lint:test` and it worked for me.

**Comment by shiraji** [comment]
You are right. I used IDE. I ran the command line `./gradlew check` and successfully make test run.

However, there is another weird problem. It doesn't execute any of my code...I added following code

``` java
public AstVisitor createJavaVisitor(JavaContext context) {
        try {
            Thread.sleep(100000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
...
}
```

the test didn't stop. Just give me it passed. Yes maybe there are issues with this lint or test cases...not sure exactly why. 

When I used LintDetectorTest, it requires .java and .class file. Does this project also require me to provide .class file to run JavaScannar lint's test case?

Sorry for out of topics. If you don't like that I would close this issue.

**Comment by a11n** [comment]
Regarding the original issue:
It's strange, cause running tests from Gradle seems to copy the resources to correct location. Running tests from IntelliJ also works. Only Android Studio is not able to find the file. However, I'm glad it's finally working for you :-)

Regarding your new question:
I remember that I'd to struggle with similar issues. This JUnit-rule is just wrapping LintDetectorTest. It's purpose is to provide JUnit4 style testing rather than extending test case and so on. So I assume it behaves like LintDetectorTest. 

By the way: Tor Norbye is recommending "inline" specification of test resources, see [1] for example. I guess a lot of "configuration" could be saved that way. 
1. https://github.com/a11n/CustomLintRules/blob/master/src/test/java/de/ad/android/tools/lint/HelloWorldDetectorTest.java

**Comment by shiraji** [comment]
Thanks for you response. I think this issue should be closed for now.

I will check the "inline" specification.
